### ISSUE TITLE
Hook up google sheets

### ISSUE THREAD

**Issue by scottdj92** [scottdj92/deaf-creator#6]
retrieve correct credentials and post it when the form is submitted

**Comment by mrawlingst** [comment]
https://www.npmjs.com/package/usa-states as suggested by Scott

**Comment by mrawlingst** [comment]
Just some research that could be useful to figuring out how to achieve this: https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server

**Comment by mrawlingst** [comment]
This is potentially lot more simpler: https://www.open-electronics.org/how-send-data-from-arduino-to-google-docs-spreadsheet/

**Comment by scottdj92** [comment]
solved by #18
